"""Data persistence for generated policies and reserve trajectories.

Created: 2026-06-08
Purpose: Export simulator and solver outputs to flat files for EDA and auditing.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.actuarial.actuarial_solver import BaseActuarialSolver
from src.actuarial.policy import Policy


def policies_to_dataframe(policies: list[Policy]) -> pd.DataFrame:
    """Flatten a list of policies into a tidy DataFrame.

    Each row represents one policy.  All metadata fields stored on the policy
    (smoker status, health tier, risk factors, net premium, etc.) are expanded
    into individual columns so they are immediately usable in EDA without
    further unpacking.

    Args:
        policies: Policies generated by PolicySimulator.

    Returns:
        pd.DataFrame: One row per policy, columns for every field.
    """
    rows: list[dict] = []
    for policy in policies:
        row: dict = {
            "policy_id": policy.policy_id,
            "age": policy.age,
            "term": policy.term,
            "premium": policy.premium,
            "pricing_interest_rate": policy.pricing_interest_rate,
            "scenario_interest_rate": policy.scenario_interest_rate,
            "interest_rate": policy.scenario_interest_rate,
            "sum_assured": policy.sum_assured,
            "mortality_source": policy.mortality_profile.source,
            # Derived actuarial quantities
            "mortality_at_inception": policy.mortality_profile.intensity_at(0.0),
            "mortality_at_midterm": policy.mortality_profile.intensity_at(policy.term / 2.0),
            "mortality_at_expiry": policy.mortality_profile.intensity_at(float(policy.term)),
            "expiry_age": policy.age + policy.term,
            "premium_to_sum_assured_ratio": policy.premium / policy.sum_assured,
        }
        row.update(policy.metadata)
        rows.append(row)
    return pd.DataFrame(rows)


def reserve_trajectories_to_dataframe(
    policies: list[Policy],
    solver: BaseActuarialSolver,
    time_steps: int,
) -> pd.DataFrame:
    """Solve and flatten reserve trajectories for every policy.

    Each row is a single (policy, time) observation.  Policy-level fields are
    repeated on every row so the DataFrame is self-contained and can be filtered
    or grouped without needing to join back to the policy table.

    Args:
        policies: Policies to solve.
        solver: Classical actuarial solver (ThieleSolver).
        time_steps: Number of time points per trajectory.

    Returns:
        pd.DataFrame: One row per (policy, time) pair.
    """
    rows: list[dict] = []
    for policy in policies:
        trajectory = solver.solve(policy, num_steps=time_steps)
        for t, v in zip(trajectory.times, trajectory.reserves):
            rows.append(
                {
                    "policy_id": policy.policy_id,
                    "time": t,
                    "reserve": v,
                    # Contextual policy fields repeated for convenient groupby/filter
                    "age": policy.age,
                    "term": policy.term,
                    "pricing_interest_rate": policy.pricing_interest_rate,
                    "scenario_interest_rate": policy.scenario_interest_rate,
                    "interest_rate": policy.scenario_interest_rate,
                    "sum_assured": policy.sum_assured,
                    "premium": policy.premium,
                    "mortality_at_t": policy.mortality_profile.intensity_at(t),
                    # Key metadata
                    "smoker_status": policy.metadata.get("smoker_status"),
                    "health_tier": policy.metadata.get("health_tier"),
                    "gender": policy.metadata.get("gender"),
                    "occupation_risk": policy.metadata.get("occupation_risk"),
                    "risk_adjustment_factor": policy.metadata.get("risk_adjustment_factor"),
                }
            )
    return pd.DataFrame(rows)


def save_datasets(
    policies_df: pd.DataFrame,
    trajectories_df: pd.DataFrame,
    output_dir: str | Path,
    fmt: str = "csv",
) -> dict[str, Path]:
    """Persist policy and trajectory DataFrames to disk.

    Args:
        policies_df: Policy-level DataFrame from ``policies_to_dataframe``.
        trajectories_df: Trajectory-level DataFrame from
            ``reserve_trajectories_to_dataframe``.
        output_dir: Directory to write files into (created if absent).
        fmt: ``"csv"`` or ``"parquet"``.  Parquet is faster and smaller for
            large portfolios; CSV is universally readable.

    Returns:
        dict[str, Path]: Mapping of ``{"policies": path, "trajectories": path}``.

    Raises:
        ValueError: If an unsupported format is requested.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    if fmt == "csv":
        policy_path = out / "policies.csv"
        traj_path = out / "reserve_trajectories.csv"
        policies_df.to_csv(policy_path, index=False)
        trajectories_df.to_csv(traj_path, index=False)
    elif fmt == "parquet":
        policy_path = out / "policies.parquet"
        traj_path = out / "reserve_trajectories.parquet"
        policies_df.to_parquet(policy_path, index=False)
        trajectories_df.to_parquet(traj_path, index=False)
    else:
        raise ValueError(f"Unsupported format '{fmt}'. Choose 'csv' or 'parquet'.")

    return {"policies": policy_path, "trajectories": traj_path}
